105 pseudonymous authorization and anonymous authorization entity categories
ukf/ukf-testbed pull request #108
Opened 2024-12-20 15:14 UTC by philsmart

This is still a WIP. Not all required checks have been added, I want to get something committed before I stop working on it for two weeks.

2025-01-16 12:04 UTC, philsmart commented
I've added the following:

- First commit 'cf9d7054b92ad8a80adee4b3a9f55bfde06ca623'
    - Tests for good SPs and IdPs that assert the entity-category or entity-category-support for Personalized Authorization, Pseudonymous Authorization and Anonymous Authorization entity categories
    - These will cause the existing rules in check_uk_mdattr to fail
- Second commit '8877a5d5b02f720da64002346d55a9bbf478969b' 
    - A proposed fix to check_uk_mdattr.xsl to include those as valid entity category values
        - All checks should now pass
    - XSL Checks for the required parts of RC3.1 and RC3.2 for both the Personalized and Pseudonymous categories and the required parts  of RC1.1 and RC1.2 for the anonymous category
        - These are in their own XSL check stages. They could, I guess, be combined into one stage.
        - These were heavily influenced by the existing R&S rules and need review for sure.
- Third commit '9e04793d9bb3c4cccd48e9065133df674588830f' 
    - Failing tests for each category that lacks DisplayName, InformationURL, or (for Personalized and Pseudonymous) PrivacyStatementURL. (RC1.1 and RC3.1)
    - Failing tests for each that lacks any ContactPerson (RC1.2 or RC3.2)
- I've not included anything for the recommended language checks as part of RC1.1 and RC3.1 (the issue suggests possible UK-specific checks for that, but we can discuss it)

2025-01-17 14:13 UTC, iay approved these changes
This looks fine to me (without looking at the spec in question, just on the basis of what you've done here).

One option we might consider is whether we want all of this nested under `mdattr` or whether a separate `ec` category might be worth inventing. That would affect the component names, file names, etc., of course so if you don't think it's worth the effort (or don't see the point) when I'm happy to treat this as an approval.

2025-01-17 14:52 UTC, philsmart commented
Thanks @iay. Yes, I think an `ec` category might be a good idea. Will wait to see what @alexstuart thinks.

2025-01-19 21:05 UTC, iay commented
Just to make it explicit, one of the things I was thinking about was that the way the test location code works:

```ruby
  def self.find_all_tests(prefix, extension)
    head = "tests/#{prefix}/"
    hlen = head.length
    elen = extension.length
    Dir.glob("#{head}**/*.#{extension}").map { |s| s[hlen..-elen - 2] }
  end
```

In this context the glob will be "`.../**/*.xml`" which will search for all XML files under the prefix no matter now nested the directories are. So one way of organising the tests would be something like `xml/ec/<specname>/`. This would allow all tests for a given entity category to be included together; not all of them will be about metadata attributes (even if that happens to be true for the current one) so putting them inside `mdattr` isn't really adding information.

If you put the files inside an `/ec/spec` directory, you don't need to include that information again in the individual test file names.

You'd probably also want to think about the names of the beans and the XSL files in the same vein: these are checks _for an entity category_ that happen to be looking at attributes and naming would be better if it reflected that.

2025-01-20 09:11 UTC, philsmart commented
I agree. I'll look to make those changes. There may be existing tests characterised larely by their filenames instead of a combination of directory structure and filename. These might also benefit from a reorgnisation. Once we are satisfied with this, I could create an issue to find and clean those up.

2025-01-24 13:32 UTC, alexstuart commented
> Thanks @iay. Yes, I think an `ec` category might be a good idea. Will wait to see what @alexstuart thinks.

I think this could be a good idea. We store the tests for an entity category in a directory `tests/xml/ec/spec/`and we use the `tests/xml/mdattr/` directory for the tests for usage of the `mdattr` container itself.

However, we've already got checks & tests for a number of entity categories, entity category support and assurance certifications directly under the top level `tests/xml`. For example, `tests/xml/rands_member`, `tests/xml/rands_support` and `tests/xml/sirtfi_v1'

Is it worthwhile adding an extra level of directories when we could just place the suitably-named directories at the `tests/xml` level?

2025-01-27 14:54 UTC, iay commented
>Is it worthwhile adding an extra level of directories when we could just place the suitably-named directories at the tests/xml level?

The more individual things you're doing, the more it makes to add some kind of organisational hierarchy. I think we're at the point where it's not _necessary_ to move the other EC tests down into a new category, but we're probably in the region where it's not a bad thing to do, particularly if we expect more ECs and tests for them in the future.

I _think_ it would just be a question of moving the directories wholesale; there shouldn't be any detailed source changes required.

2025-01-27 16:04 UTC, alexstuart commented
> The more individual things you're doing, the more it makes to add some kind of organisational hierarchy. I think we're at the point where it's not _necessary_ to move the other EC tests down into a new category, but we're probably in the region where it's not a bad thing to do, particularly if we expect more ECs and tests for them in the future.

I'm not convinced that we're at the stage where we need the extra hierarchy, nor that there'll be lots more entity categories, although I won't disagree with adding an extra layer of directories. Some pedantry:

- Do you strictly mean entity categories, or should there be seperate directories for the assurance certifications (Sirtfi v1 and v2) and SAML subject identifier signalling?
- Would entity category support be lumped in with the entity category? And would UKf-specific checks go there too? That is to say, if we were to backfill, would we put all of `rands_member`, `rands_support` and `uk_rands` into the directory?
- It might make it easier to remember there's a hierarchy if we called the directory `entity-categories` rather than `ec` (or `entity-attributes` if we were taking a more expansive view of the directory).

2025-01-27 16:21 UTC, iay commented
> > The more individual things you're doing, the more it makes to add some kind of organisational hierarchy. I think we're at the point where it's not _necessary_ to move the other EC tests down into a new category, but we're probably in the region where it's not a bad thing to do, particularly if we expect more ECs and tests for them in the future.
> 
> I'm not convinced that we're at the stage where we need the extra hierarchy,

Well, I literally said that it's not _necessary_, so we don't disagree about _need_. When to take a step like this is always a judgement call; you hold off if the amount of disruption isn't paid for by the future benefits. Here, there's little to no disruption and the benefits accrue to the existing code even if we don't have any more ECs in the future.

>nor that there'll be lots more entity categories

You're probably right about that.

> * Do you strictly mean entity categories, or should there be seperate directories for the assurance certifications (Sirtfi v1 and v2) and SAML subject identifier signalling?

I mean categories **of test**. Having one top-level directory for each group of tests is not a good long term strategy. Grouping into subdirectories by category **of test** improves comprehension and therefore maintainability. It happens that the first such directory we're considering concerns **entity categories** but that's coincidence.

So over time I'd expect us to want to move other categories of test, other than those for entity categories, into other top-level directories. Whether assurance certifications are best seen in the entity categories category, or a category of their own, or aren't worth splitting out in that way, would be a separate case by case discussion.

> * Would entity category support be lumped in with the entity category?

I think so. It's part of the individual spec, so makes sense to group them in that way.

>And would UKf-specific checks go there too?

I think intuitively yes (although I can see counter-arguments), as long as the things that are uk-specific are obviously called out in some other way, such as in the test name.

>That is to say, if we were to backfill, would we put all of `rands_member`, `rands_support` and `uk_rands` into the directory?

Proabably. Although I'd note that it's also possible to further nest them if they have some sort of important identity.

> * It might make it easier to remember there's a hierarchy if we called the directory `entity-categories` rather than `ec` (or `entity-attributes` if we were taking a more expansive view of the directory).

True. I think the only significance to the directory name is that it's included in the log line when a test is run. So they may get lengthy, but I don't think anything breaks.

2025-01-27 16:24 UTC, iay commented
>>That is to say, if we were to backfill, would we put all of rands_member, rands_support and uk_rands into the directory?
>Proabably. Although I'd note that it's also possible to further nest them if they have some sort of important identity.

I'd probably lean towards the latter, actually. Maybe not with the same names, so `entity-categories/rands/member` etc, or something of that kind.

2025-01-29 13:58 UTC, philsmart commented
I've read the comments here and want to check if my understanding aligns with the current thinking. 

- For *this* PR we move the new EC checks out of `mdattr` and into subdirectories of `/xml/entity-categories/(anonymous|personalized|pseduonumous)`.
   - For both ec and ec-support 
   - I can then simplify the test names (filenames) (the full directory structure is present in the test output log). 
 - In a separate PR we look to move other tests into an appropriate structure e.g. `entity-categories/rands/member` etc.

2025-01-29 14:17 UTC, alexstuart commented
> I've read the comments here and want to check if my understanding aligns with the current thinking.
> 
>     * For _this_ PR we move the new EC checks out of `mdattr` and into subdirectories of `/xml/entity-categories/(anonymous|personalized|pseduonumous)`.
>       
>       * For both ec and ec-support
>       * I can then simplify the test names (filenames) (the full directory structure is present in the test output log).
> 
>     * In a separate PR we look to move other tests into an appropriate structure e.g. `entity-categories/rands/member` etc.

Yes.

You should spell pseudonymous right in the filesystem though ;-)

2025-01-29 15:31 UTC, philsmart commented
OK, I have moved those over, PTAL. If it looks OK I will streamline the commits.

2025-02-06 14:38 UTC, iay approved these changes
Just reviewing on the basis of the structure.

Really like the way this has turned out, so happy to approve.

2025-03-04 15:40 UTC, philsmart commented
OK. I've made a final commit that cleans out the testing setup and leaves the tests and the changes to the default validator stages. I think this represents the final state the tests branch should be in before merging back into `main`. I've left the other commits for now, so you can see how this has progressed. It probably should be squashed before being merged.

2025-03-13 14:42 UTC, iay requested changes
I'm happy with the overall effect of this, i.e., with the final state after all four commits have been applied. However, looking through the individual commits I think we could improve the way that changes to default-validator-stages.xml are performed: things are done and later undone across the commits, probably because of the way the patch was developed, and it would probably be better to refactor so that all of that happens in one of the commits and not in the others.

The way I'd perform that refactoring personally would involve splitting each of the commits which changes that file into two, then combine all the commits for default-validator-stages. That's easy in Tower, which is the GUI tool I use in cases like this. It's probably a little more involved in the CLI, but still doable. You need to stage individual hunks but as they are all in one file it shouldn't be too bad.

2025-03-19 14:51 UTC, philsmart commented
@iay I've straightened out those commits as discussed. Could you take a final look to see if it fits expectations?

2025-03-19 16:26 UTC, merged

2025-03-19 16:43 UTC, philsmart commented
Test for Alex.