28 add tests for check hoksso
ukf/ukf-testbed pull request #29
Opened 2023-10-10 16:02 UTC by philsmart

2023-10-13 14:08 UTC, philsmart commented on tests/xml/hoksso/good_sp_hoksso.xml
> +            hoksso:ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" index="5"/>
I will fix that for these tests, as we will need specific ones when that checking ruleset is enabled.

2023-10-13 14:22 UTC, philsmart commented on tests/xml/hoksso/good_sp_hoksso.xml
> +            hoksso:ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" index="5"/>
Ok, I fixed that up

2023-10-16 11:11 UTC, iay requested changes
We talked back in August on a previous PR about non-terminated XML files and Git's slight disdain for them. I note that this has happened again this time round.

Back then you said something about not being able to sync VS Code settings across machines, so I'm assuming that's the issue here again. Can we fix these files for this commit?

Happy to accept this PR with that change (or without, actually, it's not really a big deal).

2023-10-17 11:12 UTC, philsmart commented
Added a final new line at the end of the file.

2023-10-19 15:32 UTC, iay approved these changes

2023-10-19 15:32 UTC, merged