Add tests for checking cryptographic algorithms
ukf/ukf-testbed pull request #33
Opened 2023-10-23 09:14 UTC by philsmart

2023-11-06 16:03 UTC, iay requested changes
Was the intention of this PR to add tests for all the checks in `check_uk_algorithms`? If so, I note that although it seems to cover encryption methods just fine (modulo one typo in a file name) it doesn't cover signing methods or digest methods at all.

2023-11-06 16:30 UTC, philsmart commented
It was. I must have come back to this and pushed it without completing it. Sorry about that, I will fix this.

2023-11-07 09:39 UTC, philsmart commented
Added digest and signature algorithm checks

2023-11-07 12:39 UTC, iay approved these changes

2023-11-07 14:54 UTC, merged