Add tests that check SP endpoints are protected
ukf/ukf-testbed pull request #35
Opened 2023-10-23 09:49 UTC by philsmart

2023-11-06 15:48 UTC, iay requested changes

2023-11-06 15:48 UTC, iay commented on tests/xml/sp_tls/good_sp_location_tls.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Typo in file name.

2023-11-06 16:19 UTC, philsmart commented on tests/xml/sp_tls/good_sp_location_tls.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ah yes. In the response location test.

2023-11-06 16:31 UTC, philsmart commented on tests/xml/sp_tls/good_sp_location_tls.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Fixed.

2023-11-07 12:40 UTC, iay approved these changes

2023-11-07 14:51 UTC, merged