Add Test: A SAML 2.0 IdP with an AttributeAuthority needs an AttributeService with an appropriate Binding
ukf/ukf-testbed pull request #9
Opened 2023-07-11 09:08 UTC by philsmart

- This check does not appear to have predicates which the native JDK XSLT
       processing has issues with
     - Change predicates in check_saml2.xsl to use explicit boolean operators
     - Add tests for SAML 2.0 SPs with good attribute service bindings
     - Add tests for SAML 2.0 SPs with bad attribute service bindings

See also ukfederation#383

2023-07-12 11:15 UTC, philsmart commented
Also added test: Add Test:  Use of SAML 2.0 bindings in AttributeAuthorityDescriptor requires SAML 2.0 in protocolSupportEnumeration

2023-07-17 11:05 UTC, philsmart commented
I removed the PII from these tests. I have a commit which can remove it from the other tests as well, but I will wait for this to be checked first.

2023-07-18 09:17 UTC, iay requested changes
I think I'm happy with the proposed changeset as a whole, however I think we can improve the ease of review for this and future similar changes by splitting the handling of each ruleset into three parts:

- Adding the calling of the ruleset to the pipeline, without adding any explicit tests. If this is a separate commit, it lets a reviewer check that adding the new ruleset does not break any of the checks for other rulesets. This wouldn't apply in this case because `check_saml2` was already in there from our previous commit.
- Adding the tests for the new ruleset. If this is a separate commit, it lets a reviewer run those and observe the fleet members which succeed on these tests vs. those that fail.
- Finally, the change to the ruleset which fixes it so that all fleet members succeed.

In this specific case, I think what I am asking for is for a split into two commits: one which is just the tests, and a second one which modifies `check_saml2.xsl`.

That's for the benefit of a reviewer. I'm still in two minds as to whether we should preserve that structure when we merge a PR to the main line. The alternative would be to squash after review, or at merge. We should discuss these options.

2023-07-18 09:27 UTC, philsmart commented
That makes perfect sense to me. I will write that down into a wiki page when I get a chance. I did not do something like that originally because I did not want to submit something that failed. But I see what your saying, and we can then squash down (or similar) once the review is complete.

2023-07-21 08:11 UTC, philsmart commented
I've split into two commits for adding the tests then fixing the XSL file.

2023-07-21 09:27 UTC, merged